/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

	SQUARE("[shape][SQUARE]",1500),
        TRIANGLE("[shape][TRIANGLE]",1500),
        CIRCLE("[shape][CIRCLE]",1500),
	START("[START]",1500),
	END("[END]",1500),
	RESTART("[RESTART]",1500),
	CONTINUE("[CONTINUE]",1500),
	CHECK("[CHECK]",1500),
	CALL("[CALL]",1500),
	RAISE("[RAISE]",1500),
	FOLD("[FOLD]",1500),
	ALLIN("[ALLIN]",1500),
	TABLE("[TABLE]",1500),
	HAND("[HAND]",1500),
	POT("[POT]",1500),
	LIMIT("[LIMIT]",1500),
	CASH("[CASH]",1500),
	YES("[YES]",1500);


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
